### ISSUE TITLE
conversionType==='constants' never uses the interface

### ISSUE THREAD

**Issue by pwarelis** [kreuzerk/svg-to-ts#160] opened 2022-03-18 18:47 UTC
The example output for the constants shows

```javascript
export const myIconExpressionLess: MyIcon = {
  name: 'expression_less',
  data: `<svg xmlns="http://...`
};
export const myIconFull: MyIcon = {
  name: 'full',
  data: `<svg xmlns="http://www...`
};
// etc...
```

But the reality is that the interface is never used and the output looks like this

```javascript
export const myIconExpressionLess: {
  name: 'expression_less',
  data: string
} = {
  name: 'expression_less',
  data: `<svg xmlns="http://...`
};
export const myIconFull: {
  name: 'full',
  data: string
} = {
  name: 'full',
  data: `<svg xmlns="http://www...`
};
```

Am I missing something? Tried combinations of different configurations, and finally looked at the code. The interface is never used. It this a bug?

**Comment by kreuzerk** [comment] 2022-03-20 16:21
Hi @pwarelis thx a lot for this issue. I just checked it and was able to reproduce it. Yes, this is definitely a bug.

**Comment by kreuzerk** [comment] 2022-03-20 16:32
Hi @pwarelis I just checked it locally and this is actually correct. So the interface is generated as a helper type for your functions. This means you can use it to implement a registry for example. Imagine you would want to implement a `registerIcons`function. In such a case you could use the `MyIcon` interface to type the function signature.

````

registerIcons(icons: MyIcon[]){}
````

A single icon on the other hand isn't typed with `MyIcon` because it's to generic. We type it with the actual name.

But we should definitely update the docs.

**Comment by kreuzerk** [comment] 2022-03-20 16:45
@pwarelis I updated the docs. I hope the explanation above is understandable and its okay for you if I close this Issue.

**Closed by kreuzerk** 2022-03-20 16:45 UTC
